Rol:
    type: entity
    table: rol
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        rol:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        estado:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
