Tienda:
    type: entity
    table: tienda
    indexes:
        ciudad_idx:
            columns:
                - ciudad_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        ficha:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        login:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        descripcion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        direccion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    manyToOne:
        ciudad:
            targetEntity: Ciudad
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ciudad_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
