# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
          AppBundle\Entity\Usuario:
              algorithm: bcrypt
              cost: 12


    providers:
        users_db:
            entity:
                class: AppBundle:Usuario
                property: email

    firewalls:
        login:
            pattern: ^/usuario/login$
            anonymous: ~
        frontend:
            pattern: ^/*
            security: true
            provider: users_db
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: homepage
            logout:
                path: /logout
                target: login


    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USUARIO }

