# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
          AppBundle\Entity\Usuario: bcrypt



    providers:
        users_db:
            entity:
                class: AppBundle:Usuario
                property: email

    firewalls:
        login:
            pattern: ^/usuario/login$
            anonymous: ~
        frontend:
            pattern: ^/*
            ## con anonymous hacemos que todas las url sean publicas
            anonymous: ~
            security: true
            provider: users_db
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: compras
            logout:
                path: /logout
                target: homepage
            remember_me:
                secret: cupon1234
                lifetime: 3600 ##tiempo que permanecera activa la sesion lo normal es un año


    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USUARIO }

